version: '3.7'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '${NGINX_PORT:-80}:80'
    volumes:
      - ./:/var/www/hta
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      hta:
        ipv4_address: 172.21.0.10

  hta:
    build:
      args:
        user: hta
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: hta
    restart: unless-stopped
    working_dir: /var/www/hta
    volumes:
      - ./:/var/www/hta
    networks:
      - hta
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hta
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - '${DB_PORT:-3306}:3306'
    networks:
      - hta

networks:
  hta:
    ipam:
        config:
        - subnet: 172.21.0.0/16
    driver: bridge
